### PR TITLE
Infer Sass syntax from item identifier extension, closes #1397

### LINKED ISSUE #1397: Cannot import Sass files by identifier
I use Sass syntax (not Scss). Since the new sourcemap-enabled [importer hard-codes `:scss` syntax](https://github.com/nanoc/nanoc/blob/master/nanoc/lib/nanoc/filters/sass/importer.rb#L45), I cannot use `@import` with item identifiers if the item's content syntax is Sass.

### Steps to reproduce

1. Set up [documented example](https://nanoc.ws/doc/guides/using-common-filters/#using-partials)
1. Make sure the partial contains Sass syntax-specific code
1. Compile

Example repo here: https://github.com/agross/nanoc-sass-partials-by-id

### Expected behavior

Compilation succeeds

### Actual behavior

Compilation fails

```sh
$ nanoc
Loading site… done
Compiling site…
/app.sass:4 DEBUG: Could import by relative path

Captain! We’ve been hit!

Sass::SyntaxError: Invalid CSS after "..."$this-is-sass"": expected "{", was ""

Current item: /app.sass (:default representation)

  0. /_partial.sass:3
  1. /app.sass:6
```

### Details

The build output should contain both `/app.sass:4 DEBUG: Could import by relative path` and `'Could import by item identifier'`.

I need to use `@import "/item/identifier.sass"` instead of plain files because plain files cause a dependency on all items' raw content. This essentially disables Nanoc's caching for the Sass filter output.

### Crash log

https://gist.github.com/agross/ada776af1111de4d54f5f84c81200142

### PR DESCRIPTION
**Pull request by agross**
### Detailed description

Infer Sass or Scss syntax from identifier with fallback to Scss if the identifer has no extension.

This also fixes the specs that always used Scss syntax from `CompiledContentStore`, despite of the created `TextualContent`s with the respective syntax.

### Related issues

#1397, FYI @gpakosz

### CODE REVIEW

**Comment by gpakosz** [comment]
Hello @agross 👋

I apologize, I got side-tracked and didn't look at #1397. Doing it now

File: nanoc/lib/nanoc/filters/sass/importer.rb [hunk 1]
```diff
@@ -36,13 +36,23 @@ def find(identifier, options)
...
+                            item.compiled_content,
+                          ]
+                        else
+                          import_all = items.map { |i| %(@import "#{i.identifier}";) }.join("\n")
+
+                          [
+                            :scss,
+                            import_all,
+                          ]
+                        end
```
Comment (gpakosz) [inline nanoc/lib/nanoc/filters/sass/importer.rb]: I started changing this file last week but didn't go as far as you did with updating tests.
I wrote something similar:
```
      content, syntax = if items.size == 1
                          [items.first.compiled_content, items.first.ext.downcase.to_sym || :sass]
                        else
                          [items.map { |item| %(@import "#{item.identifier}";) }.join("\n"), :scss]
                        end

      options[:syntax] = syntax
```
Which imho produces a smaller diff than yours.

I chose to make it `content, syntax` because that's somewhat what Sass does, see `find_relative()`.
I chose to make `:sass` the default syntax because that's also what Sass does.

Comment (agross) [reply nanoc/lib/nanoc/filters/sass/importer.rb]: My primary goal is to write readable code, diff size doesn't matter much to me. Git stores snapshots anyways. 😉

The fallback is `:scss` because that's what's the original code was hard-coding. 

I needed to change the specs because they were failing now that Sass compiles the inferred syntax, but the content served by the cache was Scss. 

I'm open to exchanging `syntax` and `content` if that is preferred.

Comment (gpakosz) [reply nanoc/lib/nanoc/filters/sass/importer.rb]: Readable is a subjective matter. When I talk about minimizing the diff, I talk about the cognitive load of inspecting the diff, not Git's way of storing things. I let @ddfreyne decide.

Having `content, syntax` is symetric with what Sass does and what `#find_relative()` does.

As far as the current behavior of assuming `:scss`, it's a bug and I vaguely recall my first implementation before review inspected item's extension to decide the syntax. Maybe we could `#raise()` telling we don't know which syntax to pick?

Comment (ddfreyne) [reply nanoc/lib/nanoc/filters/sass/importer.rb]: I don’t have much of an opinion here — if the tests pass and Rubocop is happy with it, then I’m happy.

File: nanoc/lib/nanoc/filters/sass/importer.rb [hunk 2]
```diff
@@ -36,13 +36,23 @@ def find(identifier, options)
...
-      content = if items.size == 1
-                  items.first.compiled_content
-                else
-                  items.map { |item| %(@import "#{item.identifier}";) }.join("\n")
-                end
+      syntax, content = if items.size == 1
+                          item = items.first
+
+                          [
+                            item.identifier.ext.downcase.to_sym || :scss,
```
Comment (ddfreyne) [inline nanoc/lib/nanoc/filters/sass/importer.rb]: I think the `|| :scss` case is not tested, and likely not correct either (if there is no extension, `.downcase` would raise a NoMethodError I expect).

Comment (agross) [reply nanoc/lib/nanoc/filters/sass/importer.rb]: Good catch! In the extensionless case Nanoc now specifies `syntax = nil` which makes Sass use its internal default (which is Sass).

File: nanoc/lib/nanoc/filters/sass/importer.rb (hunk 1 above)
Comment (agross) [reply nanoc/lib/nanoc/filters/sass/importer.rb]: @gpakosz Made the changes as requested. I also added some new specs round importing partials.

Comment (gpakosz) [reply nanoc/lib/nanoc/filters/sass/importer.rb]: @agross Thanks for the update. Well my very own opinion is that I wouldn't have traded 5 lines of code in context for 3 additional private functions (see http://number-none.com/blow/john_carmack_on_inlined_code.html). Undersanting what's going on imho now requires chasing tiny functions doing little meaningful work.

So yeah I personally would have written it differently. But if both Rubocop and @ddfreyne are happy then I'm happy too!
